version: "3"
services: 
  springboot-app:
   # container_name: spring-app
    image: springboot-app
    restart: always
    build: .
    ports:
      - 8050:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_PORT: 3306
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      -  C:\\\:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: sistema
      MYSQL_ROOT_PASSWORD: secret